language: php

php:
  - '7.1'
  - '7.2'
  - '7.3'
  - '7.4'
  - 'nightly'

cache:
  apt: true
  directories:
    - $HOME/.composer/cache

sudo: false

install:
  - if [[ $TRAVIS_PHP_VERSION = "nightly" ]]; then travis_retry composer update --prefer-dist --no-interaction --no-suggest --prefer-stable --ignore-platform-reqs; fi;
  - if [[ $TRAVIS_PHP_VERSION != "nightly" ]]; then travis_retry composer update --prefer-dist --no-interaction --no-suggest --prefer-stable; fi;

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
  - pecl install ast

script:
  - composer test

after_success:
  - bash <(curl -s https://codecov.io/bash)

after_script:
  - cp coverage.xml clover.xml
  - ./cc-test-reporter after-build --coverage-input-type clover --exit-code $TRAVIS_TEST_RESULT
  - composer require codacy/coverage
  - vendor/bin/codacycoverage clover coverage.xml

env:
  global:
    - CODACY_PROJECT_TOKEN=0a129ff74aca479ba21a16d8a316de07
    - CC_TEST_REPORTER_ID=b4c0fd2741b7cd363d1d0dac87a95b3aff1d0faaa54ec76886e1a358f6e5b86e
