language: php

php:
  - '7.1'
  - '7.2'
  - '7.3'

cache:
  apt: true
  directories:
    - $HOME/.composer/cache

sudo: false

install:
  - travis_retry composer update --prefer-dist --no-interaction --no-suggest --prefer-stable

script:
  - composer test

after_success:
  - bash <(curl -s https://codecov.io/bash)
